version: "3.9"
volumes:
    postgres_data_dev: {}

services:
  postgres:
    image: postgres
    volumes:
        - postgres_data_dev:/var/lib/postgresql/data
    environment:
        - POSTGRES_USER=$POSTGRES_USER
        - POSTGRES_HOST_AUTH_METHOD=trust

  django:
    stdin_open: true
    tty: true
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=$POSTGRES_NAME
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - USE_DOCKER=yes
    env_file: .env
    depends_on:
      - postgres

