# Generated by Django 3.2.10 on 2022-01-26 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='CRM', max_length=255, unique=True)),
            ],
            options={
                'ordering': ('-updated_at', '-created_at'),
                'get_latest_by': 'updated_at',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Accelo', max_length=255)),
                ('connection_type', models.CharField(blank=True, max_length=255, null=True)),
                ('default_ado_net_provider', models.CharField(help_text='System.Data.CData.API', max_length=255)),
                ('integration_type', models.CharField(choices=[('Source', 'Source'), ('Target', 'Target')], default='Source', max_length=20)),
                ('is_dialect', models.BooleanField(default=False)),
                ('is_dialect_over_ado_net', models.BooleanField(default=False)),
                ('is_dialect_over_odbc', models.BooleanField(default=False)),
                ('logo_url', models.CharField(help_text='Accelo.apip', max_length=255)),
                ('real_provider', models.CharField(help_text='Generic ADO.NET', max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.providercategory')),
            ],
            options={
                'ordering': ('-updated_at', '-created_at'),
                'get_latest_by': 'updated_at',
                'abstract': False,
            },
        ),
    ]
